// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package command

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 开始游戏
type CSStartGame struct {
	RoomId               uint32   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSStartGame) Reset()         { *m = CSStartGame{} }
func (m *CSStartGame) String() string { return proto.CompactTextString(m) }
func (*CSStartGame) ProtoMessage()    {}
func (*CSStartGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *CSStartGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSStartGame.Unmarshal(m, b)
}
func (m *CSStartGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSStartGame.Marshal(b, m, deterministic)
}
func (m *CSStartGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSStartGame.Merge(m, src)
}
func (m *CSStartGame) XXX_Size() int {
	return xxx_messageInfo_CSStartGame.Size(m)
}
func (m *CSStartGame) XXX_DiscardUnknown() {
	xxx_messageInfo_CSStartGame.DiscardUnknown(m)
}

var xxx_messageInfo_CSStartGame proto.InternalMessageInfo

func (m *CSStartGame) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func init() {
	proto.RegisterType((*CSStartGame)(nil), "command.CSStartGame")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 84 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x51,
	0x52, 0xe5, 0xe2, 0x76, 0x0e, 0x0e, 0x2e, 0x49, 0x2c, 0x2a, 0x71, 0x4f, 0xcc, 0x4d, 0x15, 0x12,
	0xe3, 0x62, 0x2b, 0xca, 0xcf, 0xcf, 0xf5, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0x82,
	0xf2, 0x92, 0xd8, 0xc0, 0xda, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x92, 0x53, 0x41,
	0x44, 0x00, 0x00, 0x00,
}
