// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package command

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type Online2PvpInfo struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Online2PvpInfo) Reset()         { *m = Online2PvpInfo{} }
func (m *Online2PvpInfo) String() string { return proto.CompactTextString(m) }
func (*Online2PvpInfo) ProtoMessage()    {}
func (*Online2PvpInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *Online2PvpInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Online2PvpInfo.Unmarshal(m, b)
}
func (m *Online2PvpInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Online2PvpInfo.Marshal(b, m, deterministic)
}
func (m *Online2PvpInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Online2PvpInfo.Merge(m, src)
}
func (m *Online2PvpInfo) XXX_Size() int {
	return xxx_messageInfo_Online2PvpInfo.Size(m)
}
func (m *Online2PvpInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Online2PvpInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Online2PvpInfo proto.InternalMessageInfo

func (m *Online2PvpInfo) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

//
type Pvp2OnlineInfo struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pvp2OnlineInfo) Reset()         { *m = Pvp2OnlineInfo{} }
func (m *Pvp2OnlineInfo) String() string { return proto.CompactTextString(m) }
func (*Pvp2OnlineInfo) ProtoMessage()    {}
func (*Pvp2OnlineInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *Pvp2OnlineInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pvp2OnlineInfo.Unmarshal(m, b)
}
func (m *Pvp2OnlineInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pvp2OnlineInfo.Marshal(b, m, deterministic)
}
func (m *Pvp2OnlineInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pvp2OnlineInfo.Merge(m, src)
}
func (m *Pvp2OnlineInfo) XXX_Size() int {
	return xxx_messageInfo_Pvp2OnlineInfo.Size(m)
}
func (m *Pvp2OnlineInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Pvp2OnlineInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Pvp2OnlineInfo proto.InternalMessageInfo

func (m *Pvp2OnlineInfo) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Online2PvpInfo)(nil), "command.Online2PvpInfo")
	proto.RegisterType((*Pvp2OnlineInfo)(nil), "command.Pvp2OnlineInfo")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x91,
	0xe2, 0x4d, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0x84, 0x88, 0x2b, 0x29, 0x71, 0xf1, 0xf9, 0xe7,
	0xe5, 0x64, 0xe6, 0xa5, 0x1a, 0x05, 0x94, 0x15, 0x78, 0xe6, 0xa5, 0xe5, 0x0b, 0x09, 0x70, 0x31,
	0xe7, 0x16, 0xa7, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0x98, 0x20, 0x35, 0x01, 0x65,
	0x05, 0x46, 0x10, 0x75, 0xd8, 0xd5, 0x18, 0x85, 0x71, 0x71, 0x42, 0xe4, 0x03, 0xca, 0x0a, 0x84,
	0x3c, 0xb9, 0xf8, 0xe1, 0x9c, 0xe0, 0x92, 0xa2, 0xd4, 0xc4, 0x5c, 0x21, 0x71, 0x3d, 0xa8, 0x03,
	0xf4, 0x50, 0xad, 0x93, 0x42, 0x48, 0xa0, 0xda, 0xa1, 0xc4, 0xa0, 0xc1, 0x68, 0xc0, 0x68, 0x94,
	0xc1, 0xc5, 0xeb, 0x0e, 0x71, 0x30, 0x44, 0x4a, 0x28, 0x9c, 0x4b, 0x18, 0x45, 0x00, 0x6a, 0xbe,
	0x0c, 0xdc, 0x18, 0xe7, 0x9c, 0xcc, 0xd4, 0xbc, 0x92, 0x80, 0x9c, 0xc4, 0xca, 0xd4, 0x22, 0xdf,
	0xe2, 0x74, 0x97, 0xc4, 0x92, 0x44, 0x29, 0xbc, 0xb2, 0x10, 0x9b, 0x92, 0xd8, 0xc0, 0x01, 0x62,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xb9, 0x3f, 0x84, 0x36, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OnlinePvpClient is the client API for OnlinePvp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnlinePvpClient interface {
	OnlinePvpStream(ctx context.Context, opts ...grpc.CallOption) (OnlinePvp_OnlinePvpStreamClient, error)
}

type onlinePvpClient struct {
	cc *grpc.ClientConn
}

func NewOnlinePvpClient(cc *grpc.ClientConn) OnlinePvpClient {
	return &onlinePvpClient{cc}
}

func (c *onlinePvpClient) OnlinePvpStream(ctx context.Context, opts ...grpc.CallOption) (OnlinePvp_OnlinePvpStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OnlinePvp_serviceDesc.Streams[0], "/command.OnlinePvp/OnlinePvpStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &onlinePvpOnlinePvpStreamClient{stream}
	return x, nil
}

type OnlinePvp_OnlinePvpStreamClient interface {
	Send(*Online2PvpInfo) error
	Recv() (*Pvp2OnlineInfo, error)
	grpc.ClientStream
}

type onlinePvpOnlinePvpStreamClient struct {
	grpc.ClientStream
}

func (x *onlinePvpOnlinePvpStreamClient) Send(m *Online2PvpInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *onlinePvpOnlinePvpStreamClient) Recv() (*Pvp2OnlineInfo, error) {
	m := new(Pvp2OnlineInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OnlinePvpServer is the server API for OnlinePvp service.
type OnlinePvpServer interface {
	OnlinePvpStream(OnlinePvp_OnlinePvpStreamServer) error
}

func RegisterOnlinePvpServer(s *grpc.Server, srv OnlinePvpServer) {
	s.RegisterService(&_OnlinePvp_serviceDesc, srv)
}

func _OnlinePvp_OnlinePvpStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OnlinePvpServer).OnlinePvpStream(&onlinePvpOnlinePvpStreamServer{stream})
}

type OnlinePvp_OnlinePvpStreamServer interface {
	Send(*Pvp2OnlineInfo) error
	Recv() (*Online2PvpInfo, error)
	grpc.ServerStream
}

type onlinePvpOnlinePvpStreamServer struct {
	grpc.ServerStream
}

func (x *onlinePvpOnlinePvpStreamServer) Send(m *Pvp2OnlineInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *onlinePvpOnlinePvpStreamServer) Recv() (*Online2PvpInfo, error) {
	m := new(Online2PvpInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _OnlinePvp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "command.OnlinePvp",
	HandlerType: (*OnlinePvpServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnlinePvpStream",
			Handler:       _OnlinePvp_OnlinePvpStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}

// GatewayOnlineClient is the client API for GatewayOnline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayOnlineClient interface {
	GatewayOnlineStream(ctx context.Context, opts ...grpc.CallOption) (GatewayOnline_GatewayOnlineStreamClient, error)
}

type gatewayOnlineClient struct {
	cc *grpc.ClientConn
}

func NewGatewayOnlineClient(cc *grpc.ClientConn) GatewayOnlineClient {
	return &gatewayOnlineClient{cc}
}

func (c *gatewayOnlineClient) GatewayOnlineStream(ctx context.Context, opts ...grpc.CallOption) (GatewayOnline_GatewayOnlineStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GatewayOnline_serviceDesc.Streams[0], "/command.GatewayOnline/GatewayOnlineStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayOnlineGatewayOnlineStreamClient{stream}
	return x, nil
}

type GatewayOnline_GatewayOnlineStreamClient interface {
	Send(*ClientPlayerMsgData) error
	Recv() (*ClientPlayerMsgData, error)
	grpc.ClientStream
}

type gatewayOnlineGatewayOnlineStreamClient struct {
	grpc.ClientStream
}

func (x *gatewayOnlineGatewayOnlineStreamClient) Send(m *ClientPlayerMsgData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayOnlineGatewayOnlineStreamClient) Recv() (*ClientPlayerMsgData, error) {
	m := new(ClientPlayerMsgData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayOnlineServer is the server API for GatewayOnline service.
type GatewayOnlineServer interface {
	GatewayOnlineStream(GatewayOnline_GatewayOnlineStreamServer) error
}

func RegisterGatewayOnlineServer(s *grpc.Server, srv GatewayOnlineServer) {
	s.RegisterService(&_GatewayOnline_serviceDesc, srv)
}

func _GatewayOnline_GatewayOnlineStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayOnlineServer).GatewayOnlineStream(&gatewayOnlineGatewayOnlineStreamServer{stream})
}

type GatewayOnline_GatewayOnlineStreamServer interface {
	Send(*ClientPlayerMsgData) error
	Recv() (*ClientPlayerMsgData, error)
	grpc.ServerStream
}

type gatewayOnlineGatewayOnlineStreamServer struct {
	grpc.ServerStream
}

func (x *gatewayOnlineGatewayOnlineStreamServer) Send(m *ClientPlayerMsgData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayOnlineGatewayOnlineStreamServer) Recv() (*ClientPlayerMsgData, error) {
	m := new(ClientPlayerMsgData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GatewayOnline_serviceDesc = grpc.ServiceDesc{
	ServiceName: "command.GatewayOnline",
	HandlerType: (*GatewayOnlineServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GatewayOnlineStream",
			Handler:       _GatewayOnline_GatewayOnlineStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
