// Code generated by protoc-gen-go. DO NOT EDIT.
// source: online.proto

package command

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CSStartGameOnline struct {
	RoomId               uint32   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSStartGameOnline) Reset()         { *m = CSStartGameOnline{} }
func (m *CSStartGameOnline) String() string { return proto.CompactTextString(m) }
func (*CSStartGameOnline) ProtoMessage()    {}
func (*CSStartGameOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeeec9a52ed8e15, []int{0}
}

func (m *CSStartGameOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSStartGameOnline.Unmarshal(m, b)
}
func (m *CSStartGameOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSStartGameOnline.Marshal(b, m, deterministic)
}
func (m *CSStartGameOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSStartGameOnline.Merge(m, src)
}
func (m *CSStartGameOnline) XXX_Size() int {
	return xxx_messageInfo_CSStartGameOnline.Size(m)
}
func (m *CSStartGameOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_CSStartGameOnline.DiscardUnknown(m)
}

var xxx_messageInfo_CSStartGameOnline proto.InternalMessageInfo

func (m *CSStartGameOnline) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type ServerPlayerMsgData struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ClientAddr           string   `protobuf:"bytes,3,opt,name=clientAddr,proto3" json:"clientAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPlayerMsgData) Reset()         { *m = ServerPlayerMsgData{} }
func (m *ServerPlayerMsgData) String() string { return proto.CompactTextString(m) }
func (*ServerPlayerMsgData) ProtoMessage()    {}
func (*ServerPlayerMsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeeec9a52ed8e15, []int{1}
}

func (m *ServerPlayerMsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPlayerMsgData.Unmarshal(m, b)
}
func (m *ServerPlayerMsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPlayerMsgData.Marshal(b, m, deterministic)
}
func (m *ServerPlayerMsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPlayerMsgData.Merge(m, src)
}
func (m *ServerPlayerMsgData) XXX_Size() int {
	return xxx_messageInfo_ServerPlayerMsgData.Size(m)
}
func (m *ServerPlayerMsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPlayerMsgData.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPlayerMsgData proto.InternalMessageInfo

func (m *ServerPlayerMsgData) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *ServerPlayerMsgData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ServerPlayerMsgData) GetClientAddr() string {
	if m != nil {
		return m.ClientAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*CSStartGameOnline)(nil), "command.CSStartGameOnline")
	proto.RegisterType((*ServerPlayerMsgData)(nil), "command.ServerPlayerMsgData")
}

func init() { proto.RegisterFile("online.proto", fileDescriptor_2aeeec9a52ed8e15) }

var fileDescriptor_2aeeec9a52ed8e15 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcf, 0xcb, 0xc9,
	0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc,
	0x4b, 0x51, 0xd2, 0xe6, 0x12, 0x74, 0x0e, 0x0e, 0x2e, 0x49, 0x2c, 0x2a, 0x71, 0x4f, 0xcc, 0x4d,
	0xf5, 0x07, 0xab, 0x11, 0x12, 0xe3, 0x62, 0x2b, 0xca, 0xcf, 0xcf, 0xf5, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0d, 0x82, 0xf2, 0x94, 0x52, 0xb9, 0x84, 0x83, 0x53, 0x8b, 0xca, 0x52, 0x8b,
	0x02, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0x7c, 0x8b, 0xd3, 0x5d, 0x12, 0x4b, 0x12, 0x85, 0xa4, 0xb8,
	0x38, 0x0a, 0xc0, 0x02, 0x50, 0x0d, 0x2c, 0x41, 0x70, 0xbe, 0x90, 0x10, 0x17, 0x4b, 0x4a, 0x62,
	0x49, 0xa2, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x98, 0x2d, 0x24, 0xc7, 0xc5, 0x95, 0x9c,
	0x93, 0x99, 0x9a, 0x57, 0xe2, 0x98, 0x92, 0x52, 0x24, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x19, 0x84,
	0x24, 0x92, 0xc4, 0x06, 0x76, 0xa3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xce, 0x61, 0x2b,
	0xb3, 0x00, 0x00, 0x00,
}
