// Code generated by protoc-gen-go. DO NOT EDIT.
// source: online.proto

package command

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 开始游戏
type CSStartGame struct {
	RoomId               uint32   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSStartGame) Reset()         { *m = CSStartGame{} }
func (m *CSStartGame) String() string { return proto.CompactTextString(m) }
func (*CSStartGame) ProtoMessage()    {}
func (*CSStartGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeeec9a52ed8e15, []int{0}
}

func (m *CSStartGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSStartGame.Unmarshal(m, b)
}
func (m *CSStartGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSStartGame.Marshal(b, m, deterministic)
}
func (m *CSStartGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSStartGame.Merge(m, src)
}
func (m *CSStartGame) XXX_Size() int {
	return xxx_messageInfo_CSStartGame.Size(m)
}
func (m *CSStartGame) XXX_DiscardUnknown() {
	xxx_messageInfo_CSStartGame.DiscardUnknown(m)
}

var xxx_messageInfo_CSStartGame proto.InternalMessageInfo

func (m *CSStartGame) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

//进入房间
type OPJionRoom struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OPJionRoom) Reset()         { *m = OPJionRoom{} }
func (m *OPJionRoom) String() string { return proto.CompactTextString(m) }
func (*OPJionRoom) ProtoMessage()    {}
func (*OPJionRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeeec9a52ed8e15, []int{1}
}

func (m *OPJionRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OPJionRoom.Unmarshal(m, b)
}
func (m *OPJionRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OPJionRoom.Marshal(b, m, deterministic)
}
func (m *OPJionRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OPJionRoom.Merge(m, src)
}
func (m *OPJionRoom) XXX_Size() int {
	return xxx_messageInfo_OPJionRoom.Size(m)
}
func (m *OPJionRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_OPJionRoom.DiscardUnknown(m)
}

var xxx_messageInfo_OPJionRoom proto.InternalMessageInfo

func (m *OPJionRoom) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

//
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeeec9a52ed8e15, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CSStartGame)(nil), "command.CSStartGame")
	proto.RegisterType((*OPJionRoom)(nil), "command.OPJionRoom")
	proto.RegisterType((*Empty)(nil), "command.Empty")
}

func init() { proto.RegisterFile("online.proto", fileDescriptor_2aeeec9a52ed8e15) }

var fileDescriptor_2aeeec9a52ed8e15 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcf, 0xcb, 0xc9,
	0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc,
	0x4b, 0x51, 0x52, 0xe5, 0xe2, 0x76, 0x0e, 0x0e, 0x2e, 0x49, 0x2c, 0x2a, 0x71, 0x4f, 0xcc, 0x4d,
	0x15, 0x12, 0xe3, 0x62, 0x2b, 0xca, 0xcf, 0xcf, 0xf5, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0d, 0x82, 0xf2, 0x94, 0x34, 0xb8, 0xb8, 0xfc, 0x03, 0xbc, 0x32, 0xf3, 0xf3, 0x82, 0xf2, 0xf3,
	0x73, 0x85, 0xa4, 0xb8, 0x38, 0x0a, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0xa0, 0xea, 0x58, 0x82, 0xe0,
	0x7c, 0x25, 0x76, 0x2e, 0x56, 0xd7, 0xdc, 0x82, 0x92, 0xca, 0x24, 0x36, 0xb0, 0x4d, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0xeb, 0x6a, 0x5c, 0x79, 0x00, 0x00, 0x00,
}
