// Code generated by gen_proto.sh.
// DO NOT EDIT!
package client_handler

import "app/misc/packet"
import . "app/session"

var Code = map[string]int16{
	"heart_beat_req":     2000, // 心跳包
	"user_login_req":     2001, // 登陆
	"error_ack":          2002, // 错误返回
	"licensing_card_req": 2003, // 发牌请求
	"join_room_req":      2004, // 进入房间
}

var RCode = map[int16]string{
	2000: "heart_beat_req",     // 心跳包
	2001: "user_login_req",     // 登陆
	2002: "error_ack",          // 错误返回
	2003: "licensing_card_req", // 发牌请求
	2004: "join_room_req",      // 进入房间
}

var Handlers map[int16]func(*Session, *packet.Packet) [][]byte

func init() {
	Handlers = map[int16]func(*Session, *packet.Packet) [][]byte{
		2000: P_heart_beat_req,
		2001: P_user_login_req,
		2003: P_licensing_card_req,
		2004: P_join_room_req,
	}
}
