// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package command

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 开垦土地
type CSReclamationLand struct {
	Landid               uint64   `protobuf:"varint,1,opt,name=landid,proto3" json:"landid,omitempty"`
	Toolid               uint32   `protobuf:"varint,2,opt,name=toolid,proto3" json:"toolid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSReclamationLand) Reset()         { *m = CSReclamationLand{} }
func (m *CSReclamationLand) String() string { return proto.CompactTextString(m) }
func (*CSReclamationLand) ProtoMessage()    {}
func (*CSReclamationLand) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *CSReclamationLand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReclamationLand.Unmarshal(m, b)
}
func (m *CSReclamationLand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReclamationLand.Marshal(b, m, deterministic)
}
func (m *CSReclamationLand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReclamationLand.Merge(m, src)
}
func (m *CSReclamationLand) XXX_Size() int {
	return xxx_messageInfo_CSReclamationLand.Size(m)
}
func (m *CSReclamationLand) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReclamationLand.DiscardUnknown(m)
}

var xxx_messageInfo_CSReclamationLand proto.InternalMessageInfo

func (m *CSReclamationLand) GetLandid() uint64 {
	if m != nil {
		return m.Landid
	}
	return 0
}

func (m *CSReclamationLand) GetToolid() uint32 {
	if m != nil {
		return m.Toolid
	}
	return 0
}

func init() {
	proto.RegisterType((*CSReclamationLand)(nil), "command.CSReclamationLand")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x51,
	0x72, 0xe6, 0x12, 0x74, 0x0e, 0x0e, 0x4a, 0x4d, 0xce, 0x49, 0xcc, 0x4d, 0x2c, 0xc9, 0xcc, 0xcf,
	0xf3, 0x49, 0xcc, 0x4b, 0x11, 0x12, 0xe3, 0x62, 0xcb, 0x49, 0xcc, 0x4b, 0xc9, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0xf2, 0x40, 0xe2, 0x25, 0xf9, 0xf9, 0x39, 0x99, 0x29, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x50, 0x5e, 0x12, 0x1b, 0xd8, 0x50, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x45, 0x0b, 0x50, 0x62, 0x00, 0x00, 0x00,
}
